[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_program = "4NuJXAKr6BDhqjXQLHnT5sUKtW53bv9zA2gB9hHVCET6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
